name: job_api_CICD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build_to_develop:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup for main branch
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Restore dependencies
      working-directory: ./JobListingApp/
      run: dotnet restore
    - name: Build
      working-directory: ./JobListingApp/
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./JobListingAppTests
      run: dotnet test --no-build --verbosity normal
