name: job_api_CICD_Heroku

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_to_heroku:

    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check out code
      working-directory: ./
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'joblist-api' }}
      run: |
        docker build -t joblist-api .
        docker tag joblist-api registry.heroku.com/$APP_NAME/web
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME